@SearchLoadBalancer_HostAddress = http://localhost:5075

GET {{SearchLoadBalancer_HostAddress}}/api/health
Accept: application/json

###

GET {{SearchLoadBalancer_HostAddress}}/api/lb/stats
Accept: application/json

###

POST {{SearchLoadBalancer_HostAddress}}/api/search
Content-Type: application/json

{
  "query": "socal",
  "maxAmount": 5,
  "caseSensitive": false,
  "database": "sqlite"
}

###
