apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: search-api
  namespace: searchproject
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: search-api
  namespaceSelector:
    matchNames:
      - searchproject
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
      scrapeTimeout: 4s
